# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib robustMCGARCH, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' GARCH(p = 1, q = 1) model.
#' @export
#' @section Methods:
#'\subsection{Method `new`}{
#'Create GARCH(1,1) model with specified error distribution.
#'}
#'
#'\subsection{Method `simulate`}{
#'Simulate returns and sigmas from GARCH(p = 1, q = 1) model.
#'}
#'
#'\subsection{Method `forecast`}{
#'Forecast sigmas from GARCH(p = 1, q = 1) model.
#'}
#'
GARCH <- new.env(parent = emptyenv())

GARCH$new <- function(distribution) .Call(wrap__GARCH__new, distribution)

GARCH$simulate <- function(params, n) .Call(wrap__GARCH__simulate, self, params, n)

GARCH$forecast <- function(params, returns) .Call(wrap__GARCH__forecast, self, params, returns)

GARCH$log_likelihood <- function(params, returns) .Call(wrap__GARCH__log_likelihood, self, params, returns)

#' @rdname GARCH
#' @usage NULL
#' @export
`$.GARCH` <- function (self, name) { func <- GARCH[[name]]; environment(func) <- environment(); func }

#' @export
`[[.GARCH` <- `$.GARCH`

# nolint end
