# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib robustMCGARCH, .registration = TRUE
NULL

#' GARCH(p = 1, q = 1) model.
#' @export
#' @section Methods:
#'\subsection{Method `new`}{
#'Create GARCH(1,1) model with specified white noise distribution.
#'}
#'
#'\subsection{Method `simulate`}{
#'Simulate returns and sigmas from GARCH(p = 1, q = 1) model.
#'}
#'
#'\subsection{Method `sigmas`}{
#'Calculate sigmas of GARCH(p = 1, q = 1) model.
#'}
#'
#'\subsection{Method `forecast`}{
#'Forecast one-step-ahead sigma of GARCH(p = 1, q = 1) model.
#'}
#'
#'\subsection{Method `log_likelihood`}{
#'Log-likelihood function of GARCH(p = 1, q = 1) model.
#'}
#'
#'\subsection{Method `objective`}{
#'Objective function of GARCH(p = 1, q = 1) model.
#'}
#'
GARCH <- new.env(parent = emptyenv())

GARCH$new <- function(white_noise) .Call(wrap__GARCH__new, white_noise)

GARCH$simulate <- function(params, n) .Call(wrap__GARCH__simulate, self, params, n)

GARCH$sigmas <- function(params, returns) .Call(wrap__GARCH__sigmas, self, params, returns)

GARCH$forecast <- function(params, returns) .Call(wrap__GARCH__forecast, self, params, returns)

GARCH$log_likelihood <- function(params, returns) .Call(wrap__GARCH__log_likelihood, self, params, returns)

GARCH$objective <- function(params, returns) .Call(wrap__GARCH__objective, self, params, returns)

GARCH$objective_p <- function(params, returns) .Call(wrap__GARCH__objective_p, self, params, returns)

GARCH$fit <- function(params, returns) .Call(wrap__GARCH__fit, self, params, returns)

#' @rdname GARCH
#' @usage NULL
#' @export
`$.GARCH` <- function (self, name) { func <- GARCH[[name]]; environment(func) <- environment(); func }

#' @export
`[[.GARCH` <- `$.GARCH`

#' MCGARCH model.
#' @export
MCGARCH <- new.env(parent = emptyenv())

MCGARCH$new <- function(white_noise) .Call(wrap__MCGARCH__new, white_noise)

MCGARCH$fit <- function(returns_ti, n_bins) .Call(wrap__MCGARCH__fit, self, returns_ti, n_bins)

#' @rdname MCGARCH
#' @usage NULL
#' @export
`$.MCGARCH` <- function (self, name) { func <- MCGARCH[[name]]; environment(func) <- environment(); func }

#' @export
`[[.MCGARCH` <- `$.MCGARCH`

# nolint end
